on:
  push: 
   branches: [ main ]
   tags:
       - 'v*.*.*'
  pull_request:
   branches: [ main]
   
  workflow_dispatch:
  
jobs:
   build-and-push:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
       with:
         aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws_region: us-east-1
